apiVersion: v1
kind: Service
metadata:
  name:  sakiphan-rtp-service
  namespace: sakiphan
spec:
  type: NodePort
  selector:
    app: sakiphan-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000